package com.xcesso;

import android.Manifest;
import android.telephony.SmsManager;

/**
 * Created by EG on 6/6/2018.
 */

public class Globals {

    public static final String locationCommand="location";
    public  static  final String contactCommand="contacts";
    public static  final  String profileCommand="profile";
    public  static  final  String fileCommand = "file";
    public static boolean isActive=false;
    public static String UserSharedPrefName="USER_DETAILS";
    public static final String [] permissionsList = new String[]{Manifest.permission.RECEIVE_SMS,Manifest.permission.READ_CONTACTS,Manifest.permission.SEND_SMS,Manifest.permission.ACCESS_COARSE_LOCATION,Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.WRITE_EXTERNAL_STORAGE,  Manifest.permission.READ_EXTERNAL_STORAGE};
    public  static void sendMessage(String phoneNo,String msg)
    {
        SmsManager smsManager = SmsManager.getDefault();
        smsManager.sendTextMessage(phoneNo, null, msg, null, null);

    }
    public static final String EMAIL ="officialxcesso@gmail.com";
    public static final String PASSWORD ="getmyphone";
    public static  final  String DEFAULT_EMAIL_MESSAGE="This Email is generated by Xcesso to get your files !";
    public static  final  String DEFAULT_EMAIL_SUBJECT="Xcesso";


    public static  boolean location_flag=false;
    public static boolean contacts_flag=false;
    public static boolean profile_flag=false;
    public static boolean sd_card_flag=false;


}
